InvoiceProductSystem/Models/ErrorViewModel.cs
namespace InvoiceProductSystem.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

InvoiceProductSystem/Models/InvoiceTable.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace InvoiceProductSystem.Models
{
    public class InvoiceTable
    {
        
        public int ID { get; set; }

        [Required(ErrorMessage = "Bill To is Required")]
        public string BillTo { get; set; } = "";
        
        [Key]
        [Required (ErrorMessage = "Invoice No is Required")]
        public string InvoiceNo { get; set; } = "";

       [Required (ErrorMessage = " Invoice Date is Required")] 
        public string InvoiceDate { get; set; } = "";

        [Required (ErrorMessage = "Due Date is Required")]
        public string DueDate { get; set; } = "";

        [Required (ErrorMessage = "Status is Required")]
        public string Status1 { get; set; } = "";
 
        public string Amount { get; set; } = "";

        public string InvoiceNote { get; set; } = "";

        public string AttachmentUrl { get; set; } = "";

        
        public decimal Subtotal1 { get; set; }

        
        public decimal TotalTax1 { get; set; }


        
        public decimal GrandTotal1 { get; set; }

        public virtual List<ProductTable> ProductTables { get; set; } = new List<ProductTable>();




        
        [NotMapped]
        public IFormFile Attachment { get; set; } 

        public enum PName
        {
            Samsung,
            Oppo,
            Motorola,
            Google,
            Relame,
            Vivo,
            Poco,
            Redmi,
            OnePlus,


        }

    }
}

InvoiceProductSystem/Models/ProductTable.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
namespace InvoiceProductSystem.Models
{
    public class ProductTable
    {
        public ProductTable()
        {

        }

        [Key]
        public int ProductID { get; set; }

        [Required(ErrorMessage = "Ivoice no is required")]
        [ForeignKey("InvoiceTable")]
        public string InvoiceNo { get; set; } = "";

        public virtual InvoiceTable InvoiceTable { get; private set ; }

        [Required(ErrorMessage = "Product Name is required")]
        public string ProductName { get; set; } = "";

        [Required(ErrorMessage ="Description is required")]
        //[Range(1, 500, ErrorMessage = "It should have only 500 characters")]
        public string Description1 { get; set; } = "";

        [Required(ErrorMessage ="Price is required")]
        public decimal Price { get; set; }

        [Required(ErrorMessage ="Quantity is Required")]
        public decimal Quantity { get; set; }

        
        public decimal Tax { get; set; }

        [Required]
        public decimal Total { get; set; }

        [NotMapped]
        public bool IsDeleted { get; set; } = false;

    }
}

InvoiceProductSystem/Controllers/HomeController.cs
using InvoiceProductSystem.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace InvoiceProductSystem.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

InvoiceProductSystem/Controllers/InvoiceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using InvoiceProductSystem.Data;
using InvoiceProductSystem.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Hosting;
using Microsoft.EntityFrameworkCore;

namespace InvoiceProductSystem.Controllers
{
    public class InvoiceController : Controller
    {
        private readonly InvoiceDbContext _context;
        private readonly IWebHostEnvironment _webHostEnvironment;
       
        public InvoiceController(InvoiceDbContext context ,IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
        }
        public IActionResult Index()
        {
            List<InvoiceTable> InvoiceTables;
            
         
            
              
            InvoiceTables = _context.InvoiceTables.ToList();
                return View(InvoiceTables);

           
            
        }

        [HttpGet]
        public IActionResult Create()
        {
            InvoiceTable invoiceTable = new InvoiceTable();
            invoiceTable.ProductTables.Add(new ProductTable() { ProductID = 1});
            return View(invoiceTable);

        }
        [HttpPost]
        public IActionResult Create(InvoiceTable invoiceTable)
        {
            //foreach(ProductTable productTable in invoiceTable.ProductTables)
            // {
            //  if(productTable.ProductName==null ||    productTable.ProductName.Length==0)
            //     invoiceTable.ProductTables.Remove(productTable);
            //}

            invoiceTable.ProductTables.RemoveAll(x => x.IsDeleted == true);
            UploadFile(invoiceTable);
           
            _context.Add(invoiceTable);
            _context.SaveChanges();
            return RedirectToAction("Index");

        }
        
      

        [HttpGet]
        public IActionResult Edit(string id)
        {
            InvoiceTable invoiceTable = _context.InvoiceTables
                .Include(e => e.ProductTables)
                .Where(a => a.InvoiceNo == id).FirstOrDefault();

            return View(invoiceTable);

           

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(InvoiceTable invoiceTable)
        {
            List<ProductTable> pdtails = _context.ProductTables.Where(d => d.InvoiceNo == invoiceTable.InvoiceNo).ToList();
            _context.ProductTables.RemoveRange(pdtails);
            _context.SaveChanges();

            invoiceTable.ProductTables.RemoveAll(x => x.IsDeleted == true);

           if(invoiceTable.Attachment !=null)
            {
                UploadFile(invoiceTable);
            }
            _context.Attach(invoiceTable);
            _context.Entry(invoiceTable).State= EntityState.Modified;
            _context.ProductTables.AddRange(invoiceTable.ProductTables);

            _context.SaveChanges();
             return RedirectToAction("Index");

        }


        public IActionResult Delete(string id)
        {
           var result = _context.InvoiceTables.Find(id);
            if(result != null)
            {
                _context.InvoiceTables.Remove(result);
                _context.SaveChanges();

            }
            return RedirectToAction("Index");
        }

        private void UploadFile(InvoiceTable invoiceTable)
        {
            if (invoiceTable.Attachment != null)
            {
                string folder = "Attachments/UploadedFiles/";
                folder += Guid.NewGuid().ToString() + "_" + invoiceTable.Attachment.FileName;
                invoiceTable.AttachmentUrl= folder;
                string serverFolder = Path.Combine(_webHostEnvironment.WebRootPath, folder);

                invoiceTable.Attachment.CopyTo(new FileStream(serverFolder, FileMode.Create));
            }
        }

        
        public IActionResult Details(string id)
        {
            InvoiceTable invoiceTable = _context.InvoiceTables
                .Include(e => e.ProductTables)
                .Where(a => a.InvoiceNo == id).FirstOrDefault();

            return View(invoiceTable);
        }


    }
}

InvoiceProductSystem/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

InvoiceProductSystem/Views/Invoice/Create.cshtml
@model InvoiceProductSystem.Models.InvoiceTable
@using static InvoiceProductSystem.Models.InvoiceTable



@{
    ViewData["Title"] = "Create";
}


    <style>
        
        .Total{background-image:none;}
        .Tax{background-image:none;}
        .Price{background-image:none;}
        .Quantity{background-image:none;}



    </style>



   
        <div class="card-header bg-primary text-uppercase text-white">
        <h4>Create Invoice</h4>
        </div>
   <p>

   </p>



        <form enctype="multipart/form-data" asp-action="Create">
            <div class="row">
        <div class="col-md-4">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
             <div class="form-group">
               <label class="control-label"><b>Bill To </b></label>
                <select asp-for="BillTo" class="form-control">
                    <option value="Select">Select</option>
                    <option value="Keyur">Keyur</option>
                    <option value="Mayur">Mayur</option>
                    <option value="Kishan">Kishan</option>
                    <option value="Pranali">Pranali</option>
                    <option value="Suyash">Suyash</option>
                    <option value="Sushma">Sushma</option>
                    <option value="Sudhir">Sudhir</option>
                </select>
               @*<input asp-for="BillTo" class="form-control" />*@
            <span asp-validation-for="BillTo" class="text-danger"></span>
            </div>
            

            <div class="form-group">
              <label class="control-label"><b>Invoice No</b></label>
                <input asp-for="InvoiceNo" class="form-control" />
                <span asp-validation-for="InvoiceNo" class="text-danger"></span>
           
            </div>
           

            
            
            <div class="form-group">
                 <label  class="control-label"><b>Invoice Date</b></label>
                <input asp-for="InvoiceDate" class="form-control" type="date"/>
                <span asp-validation-for="InvoiceDate" class="text-danger"></span>
            </div>
           
            
           
            <div class="form-group">
                <label  class="control-label"><b>Due Date</b></label>
                <input asp-for="DueDate" class="form-control" type="date" />
                <span asp-validation-for="DueDate" class="text-danger"></span>
            </div>
          

               
           
            <div class="form-group">
                 <label  class="control-label"><b>Status</b></label>
                <select asp-for="Status1" class="form-control">
                    <option value="Select">Select</option>
                    <option value="Draft">Draft</option>
                    <option value="Sent">Sent</option>
                    <option value="Paid">Paid</option>
                </select>
                <span asp-validation-for="Status1" class="text-danger"></span>
            </div>
          
             </div>
           </div>
            
           
            <p>

          </p>
           
             <p align="right"> 
                        <button id='btnadd' type="button" class="btn btn-sm btn-primary visible" onclick="AddItem(this)">Add New row</button>
                    </p>

            <div class="row">
                <div class="col-md-12">
            <table id="Ptable" class= "table table-striped table-sm" >
                <thead>
                    <tr>
                        
                        <th>Product Name</th>
                        <th>Description</th>
                        <th>Price</th>
                        <th>Quantity</th>
                        <th>Tax</th>    
                        <th>Total</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                 @for(int i=0;i<Model.ProductTables.Count;i++)
                    {
                        <tr id="row1">
                            
                            <td>
                                
                                <select asp-for="@Model.ProductTables[i].ProductName" class="valid form-control">
                                    <option value="Select Product">Select Product</option>
                                    <option value="Samsung">Samsung</option>
                                    <option value="Google">Google</option>
                                    <option value="Poco">Poco</option>
                                    <option value="Motorola">Motorola</option>
                                    <option value="Vivo">Vivo</option>
                                    <option value="Oppo">Oppo</option>
                                    <option value="Redmi">Redmi</option>
                                    <option value="Realme">Realme</option>

                                </select>
                                <span asp-validation-for="@Model.ProductTables[i].ProductName" class="text-danger"></span>
                            </td>
                            <td>
                                
                                <input asp-for="@Model.ProductTables[i].Description1" class="form-control" value=""/>
                                <span asp-validation-for="@Model.ProductTables[i].Description1" class="text-danger"></span>
                           
                            </td>
                                <td>
                               
                                <input asp-for="@Model.ProductTables[i].Price" class="form-control Price"  value=""/>
                                <span asp-validation-for="@Model.ProductTables[i].Price" class="text-danger"></span>
                            </td>
                            <td>
                               
                                <input asp-for="@Model.ProductTables[i].Quantity" class="form-control Quantity" onchange="Sum()" value=""/>
                                <span asp-validation-for="@Model.ProductTables[i].Quantity" class="text-danger"></span>
                            </td>
                            <td>
                            
                             <input asp-for="@Model.ProductTables[i].Tax" class="form-control Tax" value="" onchange="CalcTotal()"/>
                            </td>
                            <td>
                                 <input type="hidden" asp-for="@Model.ProductTables[i].IsDeleted"/> 
                               
                                <input asp-for="@Model.ProductTables[i].Total" class="form-control Total" readonly/>
                            </td>
                            <td>
                              

                                 <button id='btnremove-@i' type="button" class="btn btn-sm btn-danger visible" onclick="DeleteItem(this)">Remove</button>
                            </td>
                            

                        </tr>

                    }
                </tbody>
            </table>
            </div>
            </div>

         
           


              <div class="row">
        <div class="col-md-2">
          <div class="form-group">
               <label><b>Subtotal :</b></label>  
          </div>  
            </div>
            <div class="col-md-2">
                <div class="form-group">
                    <input id="subt1" asp-for="Subtotal1" class="form-control-plaintext" readonly />  
                </div>
            </div>
            </div>

            <div class="row">
            <div class="col-md-2">
                <div class="form-group">
            <label><b>Total Tax :</b></label>  
                </div>
            </div>

            <div class="col-md-2">
                <div class="form-group">
                    <input id="ttax1" asp-for="TotalTax1" class="form-control-plaintext" readonly/>  
                    </div>
            </div>
            </div>
            <div class="row">
            <div class="col-md-2">
                <div class="form-group">
       <label><b>Grand Total :</b></label>  
               
                </div>
            </div>
             
            <div class="col-md-2">
                <div class="form-group">
                     <input id="gt1" asp-for="GrandTotal1" class="form-control-plaintext" readonly/>  
                     </div>
            </div>
               </div>
              

            <div class="row">
                <div class="col-md-4">
            <label><b>Invoice Note</b></label>
             <input asp-for="InvoiceNote" class="form-control" type="text"/>
                    
         
             <div class="form-group">
                <label  class="control-label"><b>Attachment</b></label>
                <div class=custom-file>
                <input asp-for="Attachment" class="form-control custom-file-input" accept="application/pdf,application/vnd.ms-excel,application/msword,application/jpeg"/>
                <label>Allow only Excel,Doc,PDF,Image File.</label>
            </div>
            </div>
            </div>
            </div>
           
                <div class="col-4 btn-group">
               <div class="col-4 form-group text-left p-2">
            <a asp-action="Index" class="btn btn-dark">Back to List</a>
            </div>
               
            <div class="col-4 form-group text-left p-2">
                <input type="submit" value="Create" class="btn btn-success" />
            </div>
            </div>
            

        </form>
        
   


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    
    <script>


    $(".custom-file-input").on("change",function(){
            var fileName = $(this).val().split("\\").pop();
    $(this).siblings("custom-file-label").addClass("selected").html(fileName);

        });




    function DeleteItem(btn) {
    var table = document.getElementById('Ptable');
    var rows = table.getElementsByTagName('tr');
    if(rows.length == 2)
    {
        alert('There should be atleast one row');
        return;
        }
        

        $(btn).closest('tr').remove();
        
        CalcTotal();
        
        }


    function AddItem(btn)
    {
            var table= document.getElementById("Ptable");
    var rows =table.getElementsByTagName('tr');
    var rowOuterHtml =rows[rows.length-1].outerHTML;
    var lastrowIdx = rows.length-2;
    var nextrowIdx = eval(lastrowIdx) + 1;

    rowOuterHtml = rowOuterHtml.replaceAll('_' + lastrowIdx + '_', '_' + nextrowIdx + '_');
    rowOuterHtml = rowOuterHtml.replaceAll('[' + lastrowIdx + ']', '[' + nextrowIdx + ']');
    rowOuterHtml = rowOuterHtml.replaceAll('-' + lastrowIdx, '-' + nextrowIdx);

    var newRow=table.insertRow();
        newRow.innerHTML = rowOuterHtml;

    }



    function Sum()
    {
            var p = document.getElementsByClassName('Price');
    var q = document.getElementsByClassName('Quantity');
    var i;
    var sum = 0;
    for(i = 0 ;i<p.length ; i++)
    {
    sum = eval(p[i].value) * eval(q[i].value);
    document.getElementById('ProductTables_'+i+'__Total').value = sum;
                
     }
            
            
    }

    function CalcTotal()
    {

    var x = document.getElementsByClassName('Total');
    var xy = document.getElementsByClassName('Tax');
    var totalSum = 0;
    var totalTax = 0;
    var grandTotal = 0;
    var i;

    for(i = 0;i < x.length; i++)
    {
        totalSum = totalSum + eval(x[i].value);
        totalTax = totalTax + eval(xy[i].value);
        grandTotal = totalSum + totalTax;

    }


    document.getElementById('subt1').value=totalSum;
    document.getElementById('ttax1').value=totalTax;
    document.getElementById('gt1').value=grandTotal;
    return;
    }

    $(document).ready(function () {
        $('.custom-file-input').on("change", function () {
            var fileName = $(this).val().split("\\").pop();
            $(this).next('.custom-file-label').html(fileName);
        });
            });
            </script>

    
       
}

InvoiceProductSystem/Views/Invoice/Index.cshtml
@model IEnumerable<InvoiceProductSystem.Models.InvoiceTable>

@{
    ViewData["Title"] = "Index";
}

<div class="card-header bg-primary text-uppercase text-white">
        <h4>Invoice List</h4>
        </div>
   
@*<p>
    @using(Html.BeginForm("Index","Invoice",FormMethod.Get))
    {
    <b>Search By :</b>
    @Html.RadioButton("SearchBy","InvoiceNo",true) <text>Invoice No</text>
    @Html.RadioButton("SearchBy","Status1")<text>Status </text>  <br />
    @Html.TextBox("Search") <input type="submit" value="Search"/>
    }
</p>*@
<p>

</p>
<p>

      <a asp-action="Create" class="btn btn-sm btn-primary"
      >Create New Invoice </a>

</p>
<p>
  
</p>
<div>
<table class="table" id="Itable">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.First().InvoiceNo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().BillTo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().InvoiceDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().DueDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().Status1)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().Amount)
            </th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.InvoiceNo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BillTo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.InvoiceDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DueDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Status1)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.GrandTotal1)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.InvoiceNo"><img src="~/Attachments/ed.png" /></a> |
                <a asp-action="Details" asp-route-id="@item.InvoiceNo"><img src="~/Attachments/view-details.png" /></a> |
                <a asp-action="Delete" asp-route-id="@item.InvoiceNo" onclick="return confirm('Are you sure you want to delete Invoice : @item.InvoiceNo')"><img src="~/Attachments/del.png" /></a>
                
            </td>
        </tr>
}
    </tbody>
</table>

</div>

@section scripts{
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/dt-1.11.5/datatables.min.css"/>
 
<script type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.11.5/datatables.min.js"></script>

@*<script type="text/javascript" src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js"></script>>
<script type="text/javascript" src="https://cdn.datatables.net/1.11.5/js/dataTables.bootstrap4.min.js"></script>*@

<script>
$(document).ready(function(){
    $("#Itable").DataTable(
    {
       "lengthMenu": [ 5, 10, 15, 20, 25 ]
    });
});
</script>

}

InvoiceProductSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - InvoiceProductSystem</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/InvoiceProductSystem.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">InvoiceProductSystem</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                       
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Invoice" asp-action="Index">Invoices</a>
                        </li>
                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - InvoiceProductSystem - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src=~/lib/jquery/datatable/jquery-3.5.1.js></script>
    <script src=~/lib/jquery/datatable/jquery.dataTables.min.js></script>
    <script src=~/lib/jquery/datatable/dataTables.bootstrap4.min.js></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>